name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why / use case
